### ISSUE TITLE
Reparierkosten direkt auf Bank

### ISSUE THREAD

**Issue by KillerJund123** [MetalSystem11/MicheCortesCommunity#24]
Liebes MicheCortes Team.

 

Ich bin ein FARA Mitarbeiter und würde mir wünschen das die Reparierkosten direkt auf das Bankkonto der FARA Mitarbeiter drauf gehen.

 

Euer FARA Mitarbeiter / Spieler Tom Rudenstein

**Comment by MetalSystem11** [comment]
erledigt und wieder auf 500 Erhöht
