### ISSUE TITLE
Verkäferte Fahrzeuge vorerst entfernen

### ISSUE THREAD

**Issue by Detrox2653** [MetalSystem11/MicheCortesCommunity#26]
Heute ist es passiert. Ich sitze als Zivi mit in einem GMC Abschleppwagen und beim entladen geht alles in die Luft.
Desweiteren sieht man beim UAZ 3303 den Beifahrer nicht.

Ich empfehle die verkäferten Fahrzeuge aus dem Spiel voerst zu entfernen.

**Comment by MetalSystem11** [comment]
http://michecortes.de/forum/?view=thread&id=319#postid-730
