### ISSUE TITLE
FARA Verbesserungsvorschläge

### ISSUE THREAD

**Issue by KillerJund123** [MetalSystem11/MicheCortesCommunity#30]
Ich hätte gerne diese Punkte:

FARA:

	-Mehr Fahrzeuge (Ford Crown Victoria)

	-Mehr Absperrungen

	-Mehr Gehalt

	-Alle Fahrzeuge geskinet (RTW)

**Comment by MetalSystem11** [comment]
Ford Crown Victoria wird es für die FARA nicht geben, aber andere Fahrzeuge

Mehr Absperrungen habt ihr schon bekommen, bei genauen Wünschen bitte erneut melden

FARA hat kaum Ausgaben und man bekommt alle 5min 56$ und das als Cadett, man soll durch den Beruf nicht reich werden

Mit dem RTW haben wir derzeit Probleme, was wir aber auch schon gesagt haben
