### ISSUE TITLE
Abschleppwagen

### ISSUE THREAD

**Issue by LekuhLP** [MetalSystem11/MicheCortesCommunity#7]
Es gibt leider viele autos die sich mit dem Abschleppwagen  nicht abschleppen lassen und dan leider auch mal stehen bleiben müssen

**Comment by MetalSystem11** [comment]
Viele Autos lassen sich garnicht abschleppen

Bei manchen Autos, kommt es beim Abladen vor, das diese in die Luft fliegen und ggf. Spieler töten

**Comment by MetalSystem11** [comment]
http://michecortes.de/forum/?view=thread&id=319#postid-730
